(()=>{
const D={
nastoyki:[["Клубника — базилик", "водка • клубника • базилик • сахарный сироп", "Ягодная свежесть с травяным акцентом", "179 ₽", "tinct1.svg", "hit"], ["Банан — сливки", "водка • банан • молоко • сливки • сахар", "Мягкий, сливочный, сладкий баланс", "179 ₽", "tinct2.svg", ""], ["Киви — мята", "водка • киви • лайм • мята • сахар", "Лёгкий, освежающий, с яркой кислинкой", "179 ₽", "tinct3.svg", ""], ["Апельсин — чили", "водка • апельсин • чили • сахарный сироп", "Яркий, пряный, с согревающим послевкусием", "179 ₽", "tinct4.svg", ""], ["Облепиховая", "водка • облепиха • апельсин • мёд • корица • ваниль", "Солнечная, пряная и насыщенная", "179 ₽", "tinct1.svg", "warm"], ["Мёд — горчица", "водка • мёд • горчица • лимон • специи", "Неожиданное сочетание сладости и остроты", "179 ₽", "tinct4.svg", "warm"], ["Кофе — сливки", "водка • кофе • шоколадное молоко • сливки • сгущёнка • ваниль", "Плотная, десертная и бархатистая", "179 ₽", "tinct2.svg", "coffee"], ["Огуречная", "водка • свежий огурец • укроп • чеснок • специи", "Свежая, зелёная и гастрономичная", "179 ₽", "tinct3.svg", "fresh"], ["Чесночно-перцовая", "водка • чеснок • красный перец", "Смелая, пряная и согревающая", "179 ₽", "tinct4.svg", "dark"], ["Халва", "водка • халва • сливки • молоко", "Мягкая, сливочная, с восточным характером", "179 ₽", "tinct2.svg", "cream"], ["Сникерс", "водка • Snickers • сливки • сгущёнка • сахар", "Десерт в формате настойки", "179 ₽", "tinct2.svg", "coffee"], ["Вишня — мускатный орех", "водка • вишня • корица • мускатный орех • сахар", "Насыщенная вишня и тёплые специи", "179 ₽", "tinct1.svg", "dark"]],
cocktails:[["Розовая пантера", "водка • амаретто • клубника • гренадин • сливки", "289 ₽"], ["Секс на пляже", "водка • ананас • персик • вишня • сахарный сироп", "289 ₽"], ["Джин Санрайз", "джин • ананас • клубника", "289 ₽"], ["Пина Колада", "водка • ананас • кокос • сливки", "289 ₽"], ["Космополитен", "водка • трипл-сек • вишня • лимон", "289 ₽"], ["Клубничный мохито", "джин • клубника • лайм • мята • Sprite", "289 ₽"], ["Барби", "водка • вишня • Sprite", "289 ₽"], ["Как назовёшь, так и поедет", "водка • ананас • апельсин • сливки • гренадин", "289 ₽"], ["Бора-Бора", "водка • ананас • лайм • Blue Curaçao • лимон", "289 ₽"], ["Корсика", "джин • грейпфрут • лимон • малина • апельсин", "289 ₽"], ["Виски-кола", "виски • кола", "289 ₽"], ["Лонг-Айленд", "водка • ром • текила • джин • апельсиновый ликёр • лимон • кола", "289 ₽"], ["Текила Бум", "текила • Sprite", "289 ₽"], ["Самбука", "самбука • кофейные зёрна", "289 ₽"]],
shots:[["Привидение", "водка • дынный ликёр • Blue Curaçao", "199 ₽"], ["Ириска", "сливочный ликёр • Jägermeister", "199 ₽"], ["Тик-Так", "водка • ананас • клубника • лайм", "199 ₽"], ["ТАНЦЫ", "Jägermeister • апельсин • гренадин", "199 ₽"], ["B-52", "кофейный ликёр • сливочный ликёр • трипл-сек", "199 ₽"], ["Камикадзе", "водка • Blue Curaçao • лимон", "199 ₽"], ["Боярский", "водка • гренадин • Tabasco", "199 ₽"], ["Серебряная пуля", "текила • кофейный ликёр", "199 ₽"]],
food:{"ЗАКУСКИ": [["Соленья", "Скоро в продаже"], ["Сырная нарезка", "220 ₽"], ["Мясная нарезка", "250 ₽"], ["Колбасная нарезка", "260 ₽"], ["Рыбная нарезка", "500 ₽"], ["Жареные гренки", "Скоро в продаже"], ["Салат «Цезарь»", "350 ₽"], ["Канапе", "Скоро в продаже"], ["Ассорти брускетт — 3 шт. (овощная, рыбная, мясная)", "280 ₽"]], "ФРИТЮР": [["Сырные палочки", "Скоро в продаже"], ["Стрипсы", "Скоро в продаже"], ["Наггетсы лёгкая (4–5 шт.)", "130 ₽"], ["Наггетсы стандарт (6–8 шт.)", "200 ₽"], ["Наггетсы большая (9–12 шт.)", "310 ₽"], ["Крылья в панировке лёгкая (3–4 шт.)", "250 ₽"], ["Крылья в панировке стандарт (5–6 шт.)", "380 ₽"], ["Крылья в панировке большая (8–9 шт.)", "570 ₽"], ["Луковые кольца лёгкая (6–8 шт.)", "120 ₽"], ["Луковые кольца стандарт (10–12 шт.)", "180 ₽"], ["Луковые кольца большая (14–16 шт.)", "250 ₽"], ["Кольца кальмара", "Скоро в продаже"], ["Картофель фри", "100 ₽"]], "ГРИЛЬ": [["Шашлык из свинины (100 г)", "230 ₽"], ["Овощи гриль", "Скоро в продаже"], ["Шампиньоны гриль", "Скоро в продаже"]]},
drinks:[["Компот (1 л)", "250 ₽", ""], ["Сок", "—", "Уточняйте наличие у официанта"]],
hookah:[["Тяжёлый фреш", "1200 ₽", "свежий, плотный и без компромиссов"], ["Средний фруктовый", "1000 ₽", "фрукты здесь явно не ради витаминов"], ["Лёгкий десертный", "900 ₽", "сладко, мягко, почти невинно"]]
};
const names={nastoyki:'НАСТОЙКИ',cocktails:'КОКТЕЙЛИ',shots:'ШОТЫ',food:'КУХНЯ',drinks:'НАПИТКИ',hookah:'КАЛЬЯН'};
const intros={nastoyki:'Наши настойки — ручная работа и натуральные ингредиенты.',cocktails:'Классика, настроение и немного хорошего безрассудства.',shots:'Коротко, ярко и без лишних разговоров.',drinks:'Когда хочется просто освежиться.',hookah:'Выбирай характер — дальше дым всё решит сам.'};
const meta={nastoyki:'12 ПОЗИЦИЙ',cocktails:'14 ПОЗИЦИЙ',shots:'8 ПОЗИЦИЙ',food:'ЗАКУСКИ • ФРИТЮР • ГРИЛЬ',drinks:'БЕЗАЛКОГОЛЬНЫЕ',hookah:'3 НАСТРОЕНИЯ'};
const home=document.getElementById('homeView'), sectionView=document.getElementById('sectionView'), content=document.getElementById('sectionContent'), title=document.getElementById('topTitle'), left=document.getElementById('leftSlot'), right=document.getElementById('rightSlot');
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function head(id){return `<div class="section-head"><h2>${names[id]}</h2><span>${meta[id]}</span></div>`}
function note(text){return `<p class="section-intro">${text}</p>`}
function bottom(a,b=''){return `<div class="bottom-note"><div class="line1">${a}</div>${b?`<div class="line2">${b}</div>`:''}</div>`}
function renderNast(){
  const photos=['p1','p2','p3','p4','p1 warm','p4 warm','p2 coffee','p3 fresh','p4 dark','p2 cream','p2 coffee','p1 dark'];
  return head('nastoyki')+note(intros.nastoyki)+D.nastoyki.map((x,i)=>`<article class="tincture-row"><div class="tincture-photo ${photos[i]}" aria-hidden="true"></div><div class="tincture-copy">${i===0?'<span class="badge">ХИТ</span>':''}<div class="tincture-head"><h3>${esc(x[0])}</h3><strong>${x[3]}</strong></div><p class="ingredients">${esc(x[1])}</p><p class="mood">${esc(x[2])}</p></div></article>`).join('')+bottom('Наливаем с душой. Отдыхаем с характером.','ЧАПЛЫГИН • СОВЕТСКАЯ, 23А');
}
function rows(id,feature=-1){
 return head(id)+note(intros[id])+D[id].map((x,i)=>`<article class="menu-item${i===feature?' feature':''}"><div><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p></div><strong>${x[2]}</strong></article>`).join('')+bottom(id==='cocktails'?'Что выбрать — подскажем за баром.':'Один шот — это ещё не история. Но хорошее начало.');
}
function renderFood(){
 let s=head('food')+`<div class="food-atmo"><p>ГОРЯЧЕЕ. СЫТНОЕ. НАСТОЯЩЕЕ.<small>вкус, проверенный вечером</small></p></div>`;
 Object.entries(D.food).forEach(([g,items])=>{s+=`<h3 class="group-title">${g}</h3>`+items.map(x=>`<article class="food-row"><span>${esc(x[0])}</span><strong class="${x[1].includes('Скоро')?'soon':''}">${esc(x[1])}</strong></article>`).join('')});
 return s+bottom('Блюда готовим и подаём с настроением.');
}
function renderDrinks(){
 return head('drinks')+note(intros.drinks)+D.drinks.map(x=>`<article class="menu-item"><div><h3>${esc(x[0])}</h3>${x[2]?`<p>${esc(x[2])}</p>`:''}</div><strong>${x[1]}</strong></article>`).join('');
}
function renderHookah(){
 return head('hookah')+note(intros.hookah)+D.hookah.map((x,i)=>`<article class="hookah-card${i===0?' feature':''}"><div class="tincture-head"><h3>${esc(x[0])}</h3><strong>${x[1]}</strong></div><p>${esc(x[2])}</p></article>`).join('')+bottom('Бронь столов','<a href="tel:+79969287820">8 996 928-78-20</a> • 18:00–03:00');
}
function render(id){if(id==='nastoyki')return renderNast();if(id==='cocktails')return rows(id,7);if(id==='shots')return rows(id,3);if(id==='food')return renderFood();if(id==='drinks')return renderDrinks();return renderHookah()}
function homeMode(push=true){
 home.style.display='block';sectionView.classList.remove('active');content.innerHTML='';title.textContent='ВЫСОКИЙ ГРАДУС';left.innerHTML='<div class="monogram">ВГ</div>';right.innerHTML='<div class="burger" aria-hidden="true"><i></i><i></i><i></i></div>';document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));if(push)history.pushState(null,'',location.pathname+location.search);scrollTo(0,0)
}
function sectionMode(id,push=true){
 if(!names[id])return;home.style.display='none';sectionView.classList.add('active');content.innerHTML=render(id);title.textContent=names[id];left.innerHTML='<button type="button" id="backBtn" aria-label="Назад">←</button>';right.innerHTML='<button type="button" id="homeBtn" aria-label="Главное меню">⌂</button>';document.getElementById('backBtn').onclick=()=>homeMode(true);document.getElementById('homeBtn').onclick=()=>homeMode(true);document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.section===id));if(push)history.pushState(null,'','#'+id);scrollTo(0,0);const active=document.querySelector(`.tab[data-section="${id}"]`);if(active)active.scrollIntoView({inline:'center',block:'nearest'})
}
document.querySelectorAll('[data-section]').forEach(el=>el.addEventListener('click',()=>sectionMode(el.dataset.section,true)));
window.addEventListener('popstate',()=>{const id=location.hash.slice(1);id&&names[id]?sectionMode(id,false):homeMode(false)});
const id=location.hash.slice(1);id&&names[id]?sectionMode(id,false):homeMode(false);
})();